name: Android NDK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Check NDK info
      run: |
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_NDK: $ANDROID_NDK"
        echo "ANDROID_NDK_ROOT: $ANDROID_NDK_ROOT"
        echo "NDK version: $(ls $ANDROID_NDK/../ndk/)"
        echo "Listing contents of toolchain bin directory:"
        ls -la "$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin"
    
